# -*- coding: utf-8 -*-
"""DES.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxxvjgs9mh1cyCVfWbs8ckCcJNtG6FZ_
"""

! pip install pyDes

! pip install opencv-python

!pip install pillow

import pyDes
import numpy as np
import io
import base64
import cv2
import PIL.Image as Image
from matplotlib import pyplot as plt

 
# load the image and convert into numpy array
#img = Image.open('winged-hussar.jpg')

key=input("Insert the key: ")
 
#Pass image to byte array
with open("winged-hussar.jpg", "rb") as image:
  f = image.read()
  b = bytes(f)

#Declare DES object
DES=pyDes.des(key,padmode=pyDes.PAD_PKCS5)
#Encode image using DES
cryptedImage=DES.encrypt(b)

print()
print("DES encryption: ")
print(cryptedImage)

#Encode image using Base 64
b64Image=base64.b64encode(cryptedImage)

print()
print("Base 64 encryption: ")
print(b64Image)

#Decrypt Base 64
decryptedImageB64=base64.b64decode(b64Image)

#Decrypt DES
decryptedImage=DES.decrypt(decryptedImageB64)

np_jpg = np.frombuffer(decryptedImage, dtype=np.uint8)
img2 = cv2.imdecode(np_jpg, flags=1)
cv2.imwrite('decryptedImage.jpg', img2)

img_color = cv2.imread('decryptedImage.jpg',1)
plt.imshow(cv2.cvtColor(img_color, cv2.COLOR_BGR2RGB))
plt.axis("off")
plt.show()